package weber.kaden.common.command;


public enum CommandType {
    LOGIN, REGISTER, CREATEGAME, JOINGAME, STARTGAME, GETTURNS, POLLGAMESLIST, POLLGAME, LEAVEGAME, CHAT, DRAWDESTINATIONCARDS, DRAWTRAINCARDS
}
