package weber.kaden.common.model;

public enum City {
    VANCOUVER, CALGARY, WINNIPEG, SAULT_ST_MARIE, MONTREAL, BOSTON, NEW_YORK, TORONTO, SAINT_LOUIS,
    DULUTH, HELENA, SEATTLE, PORTLAND, SAN_FRANCISCO, SALT_LAKE_CITY, LAS_VEGAS, LOS_ANGELES,
    PHOENIX, SANTA_FE, EL_PASO, HOUSTON, DALLAS, OKLAHOMA_CITY, DENVER, KANSAS_CITY, OMAHA, CHICAGO,
    PITTSBURGH, WASHINGTON, RALEIGH, NASHVILLE, LITTLE_ROCK, NEW_ORLEANS, MIAMI, CHARLESTON, ATLANTA
}
